const strings = {
  productsEyebrow: "Direto do estoque",
  productsTitle: "Destaques da semana",
  productsDescription:
    "Alguns dos itens mais pedidos no Direct — confirme disponibilidade antes de fechar o pedido.",
  productsLoadFailedTitle: "Algo deu errado",
  productsLoadFailedSub: "Não foi possível carregar os produtos.",
  productsRetry: "Tentar novamente",
  categoriesEyebrow: "O que você encontra aqui",
  categoriesTitle: "Categorias",
  categoriesDescription:
    "Uma seleção pensada para todo tipo de fumante — do iniciante ao mais exigente.",
  cartTitle: "Carrinho",
  cartEmptyTitle: "Seu carrinho está vazio",
  cartEmptySub: "Explore o estoque e escolha seus favoritos.",
  viewProducts: "Ver produtos",
  decreaseQuantity: "Diminuir quantidade",
  increaseQuantity: "Aumentar quantidade",
  removeItem: (name: string) => `Remover ${name}`,
  totalLabel: "Total",
  cartCheckout: "Finalizar Pedido",
  checkoutTitle: "Finalizar Pedido",
  cardNumberLabel: "Número do Cartão",
  expiryLabel: "Validade",
  cvvLabel: "Código de segurança",
  cardNameLabel: "Nome do Titular",
  cardNumberPlaceholder: "4111 1111 1111 1111",
  expiryPlaceholder: "MM/AA",
  cvvPlaceholder: "123",
  cardNamePlaceholder: "Maria Silva",
  processingPayment: "Processando pagamento...",
  paymentConfirmedTitle: "Pagamento Confirmado!",
  paymentSuccessMessage: (total: number) =>
    `Seu pedido de R$ ${total.toFixed(2).replace(".", ",")} foi processado com sucesso.`,
  continueShopping: "Continuar Comprando",
  payButton: (total: number) =>
    `Pagar R$ ${total.toFixed(2).replace(".", ",")}`,
  cardNumberError: "O número deve ter 16 dígitos",
  expiryError: "Validade deve estar no formato MM/AA",
  cvvError: "O código deve ter 3 dígitos",
  cardNameError: "Informe o nome no cartão",
  paymentDeclined: "Pagamento recusado. Tente novamente.",
};

export default strings;
